### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by linqq9** [csyourui/bgi-llm-promptcblue#1]
大佬你好啊，最近想学习一下你的代码，但是发现[CCKS2023-PromptCBLUE中文医疗大模型评测基准—开源赛道]已经结束了，数据集无法下载，请问你那边有保存么，可以麻烦分享我一份嘛

**Comment by csyourui** [comment]
这个比赛已经结束挺久了，官方修改数据举办了第二次比赛，后续也没有继续参加了，上传了目前从官网下载的四个数据[官方数据集](https://github.com/csyourui/bgi-llm-promptcblue/tree/main/data/%E5%AE%98%E6%96%B9%E5%8E%9F%E5%A7%8B%E6%95%B0%E6%8D%AE%E9%9B%86)，仅供学习参考~
