### ISSUE TITLE
全部token计算loss的代码

### ISSUE THREAD

**Issue by vincentlbj** [csyourui/bgi-llm-promptcblue#2]
请问下哪部分的代码是做这个修改的："区别于通用的sft方案，我们在计算loss按照预训练的策略对于全部的token均计算了loss"

**Comment by csyourui** [comment]
这里有两个`tokenize`的函数
https://github.com/csyourui/bgi-llm-promptcblue/blob/873a53ffa01116cccd6f65953247a65e88628019/src/bgillm/data/qadata.py#L110-L135
下面那个就是通用的，对输入的问题设置`label=-100`从而忽略

再在下面根据参数选择不同的函数
https://github.com/csyourui/bgi-llm-promptcblue/blob/873a53ffa01116cccd6f65953247a65e88628019/src/bgillm/data/qadata.py#L140

ps.这个单纯是我们在这个比赛中实验的结果，可能不具有普遍性，通常来说对于问题的token进行忽略的目的是保证模型不去预测问题，但可能也是因为这个比赛的问题模式有限，尝试去预测问题+答案可能更好

**Comment by vincentlbj** [comment]
好的谢谢，回答的特别详细
